CREATE TABLE IF NOT EXISTS public.directors
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    PRIMARY KEY (id)
);


ALTER TABLE IF EXISTS public.movies
    ADD FOREIGN KEY (director_id)
        REFERENCES public.directors (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
        NOT VALID;

END;