CREATE TABLE IF NOT EXISTS movies
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL,
    year integer NOT NULL,
    director_id integer NOT NULL,
    PRIMARY KEY (id)
);